### ISSUE TITLE
Does not work as per instructions!

### ISSUE THREAD

**Issue by hindsa-nabeel** [DrDonk/unlocker#3]
"press any key to continue" prints they key pressed, only Return key will continue.

**Comment by DrDonk** [comment]
The message has been fixed in the next release. Thanks.

**Comment by hindsa-nabeel** [comment]
I downloaded the latest (4.1) but still get the same response.
Sorry, I just relised that ENTER is the required key now..
I guess issue is closed.

**Comment by DrDonk** [comment]
4.1.0 hasn't been released yet, but I have changed the message to specify it is the Enter key in that code.
