### ISSUE TITLE
Stuck in `getting vmware tools...`

### ISSUE THREAD

**Issue by insaneshadowzaman** [DrDonk/unlocker#36]
When I run the command `./lnx-install.sh` in the terminal, all goes ok but after `Getting VMware Tools...`, nothing happens. I have waited for about half an hour.
Using manjaro deepin as my os. 
Latest version of vmware 15.
Using latest commit of unlocker.

**Comment by insaneshadowzaman** [comment]
But running `python2 gettools.py` works fine. So I manually ran the python scripts

**Comment by DrDonk** [comment]
This was fixed in 3.0.2.

**Comment by lechautu** [comment]
Hi i'm using unlocker 3.0.2 on Win10 with workstation 15 and still having this issue. I tried uninstalling and installing it over and over again, turns out It's random, sometimes it works sometimes not. Dunno why
